--  CREATE DATABASE RealEstate;

USE RealEstate;

-- CREATE NEW USER. UNCOMMENT FOR NEW INSTALL.
DROP USER 'rewebuser'@'localhost';

CREATE USER 'rewebuser'@'localhost' IDENTIFIED BY 'rewebuser';
GRANT INSERT,SELECT,UPDATE,DELETE ON RealEstate.* TO 'rewebuser'@'localhost';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS Content;
DROP TABLE IF EXISTS Content;
CREATE TABLE Content(
   Id INT NOT NULL AUTO_INCREMENT,
   Name VARCHAR(100) NOT NULL,
   Data VARCHAR(21844) NOT NULL,
   LastModified TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( Id )
);

-- DROP TABLE IF EXISTS members;
-- DROP TABLE IF EXISTS members;
-- CREATE TABLE members (
--   `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `username` VARCHAR(30) NOT NULL,
--   `email` VARCHAR(50) NOT NULL,
--   `password` CHAR(128) NOT NULL,
--   `salt` CHAR(128) NOT NULL 
-- );

-- DROP TABLE IF EXISTS LoginAttempts;
-- DROP TABLE IF EXISTS LoginAttempts;
-- CREATE TABLE LoginAttempts (
--   `user_id` INT(11) NOT NULL,
--   `time` VARCHAR(30) NOT NULL
-- );

DROP TABLE IF EXISTS ListingImages;
DROP TABLE IF EXISTS Listings;
CREATE TABLE Listings (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Address VARCHAR(200) NOT NULL,
  City VARCHAR(50) NOT NULL,
  Province VARCHAR(50) NOT NULL,
  Country VARCHAR (200) NOT NULL,
  Description VARCHAR(21844) NOT NULL,
  Price NUMERIC(15,2) NOT NULL,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PropertyType VARCHAR(50) NULL,
  Bedrooms VARCHAR(50) NOT NULL,
  Bathrooms INT NOT NULL,
  LivingSpace INT NOT NULL,
  LandSize INT NULL,
  TaxYear INT NULL,
  Taxes NUMERIC(15,2) NULL,
  BuildingAge INT NULL,
  New BIT NULL,
  Sold BIT NULL,
  Published BIT NULL,
  Latitude Double NULL,
  Longitude Double NULL,
  Featured BIT NULL
);

CREATE TABLE ListingImages (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ListingId INT NOT NULL,
  FOREIGN KEY (ListingId) 
        REFERENCES Listings(Id)
        ON DELETE CASCADE,
  Name VARCHAR(200) NOT NULL,
  Featured BIT NULL
);